use_frameworks!

target 'HaventecCommon_Example' do
  pod 'HaventecCommon', :path => '../'

  target 'HaventecCommon_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
